#!/usr/bin/env bash
export DISPLAY=:0
BAR_ID=$(pgrep -x waybar)

if [ -e $HOME/.config/hypr/component/waybar/config_is_detailed ]
then
    kill -TERM ${BAR_ID}
    pkill -ALRM sxhkd
	waybar -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &
	rm -f $HOME/.config/hypr/component/waybar/config_is_detailed
else
    kill -TERM ${BAR_ID}
    pkill -ALRM sxhkd
	waybar -c $HOME/.config/hypr/component/waybar/config_detailed -s $HOME/.config/hypr/component/waybar/style.css &
	touch $HOME/.config/hypr/component/waybar/config_is_detailed
fi

