#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
#$scripts/tools/dynamic &

# wallpaper
#$scripts/wall $config/wallpapers/cloud.png &
$scripts/wall $config/wallpapers/gruv4.png &

# effects
#$scripts/rgb &

# other
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

#setxkbmap -option caps:escape
xrdb ~/.Xresources
#gsettings set org.gnome.desktop.interface gtk-theme "gruvbox-dark-gtk"
rm -f $HOME/.config/hypr/component/waybar/config_is_detailed
greenclip daemon
