local api = require("source.api")
local config = require("config")
local credentials = require("source.credentials")

describe("source.api.argv", function()
	it("builds a curl command without a shell", function()
		local argv = api.argv(config.resolve({ timeout = 7, api_url = "http://x/usage" }), "TOK")
		assert_eq(argv[1], "curl")
		assert_eq(argv[4], "7")
		assert_eq(argv[6], "Authorization: Bearer TOK")
		assert_eq(argv[8], "anthropic-beta: oauth-2025-04-20")
		assert_eq(argv[#argv], "http://x/usage")
	end)
end)

describe("source.api.interpret", function()
	it("decodes a 200 body", function()
		local ok, data = api.interpret('{"five_hour":{"utilization":5}}\n200', "", "exit", 0, 1)
		assert_true(ok)
		assert_eq(data.five_hour.utilization, 5)
	end)
	it("classifies status codes", function()
		local _, e = api.interpret("\n401", "", "exit", 0, 1)
		assert_eq(e.code, "unauthorized")
		_, e = api.interpret("\n403", "", "exit", 0, 1)
		assert_eq(e.code, "unauthorized")
		_, e = api.interpret("rate\n429", "", "exit", 0, 1)
		assert_eq(e.code, "rate_limited")
		_, e = api.interpret("\n503", "", "exit", 0, 1)
		assert_eq(e.code, "network")
		_, e = api.interpret("\n418", "", "exit", 0, 1)
		assert_eq(e.code, "parse")
	end)
	it("treats curl failures as network errors", function()
		local _, e = api.interpret("", "curl: (6) Could not resolve host: api.anthropic.com", "exit", 6, 1)
		assert_eq(e.code, "network")
		assert_eq(e.message, "Could not resolve host: api.anthropic.com")
	end)
	it("rejects invalid JSON and missing status", function()
		local _, e = api.interpret("not json\n200", "", "exit", 0, 1)
		assert_eq(e.code, "parse")
		_, e = api.interpret("{}", "", "exit", 0, 1)
		assert_eq(e.code, "parse")
	end)
end)

describe("source.credentials", function()
	it("reads a valid file", function()
		local c, err = credentials.read("spec/fixtures/credentials_ok.json", 1758560000)
		assert_nil(err)
		assert_eq(c.token, "REDACTED-TOKEN")
		assert_eq(c.subscription, "max")
		assert_eq(c.expires_at, 4102444800)
	end)
	it("reports an expired token without exposing it", function()
		local c, err = credentials.read("spec/fixtures/credentials_expired.json", 1758560000)
		assert_nil(c)
		assert_eq(err.code, "unauthorized")
	end)
	it("reports a missing file", function()
		local c, err = credentials.read("spec/fixtures/does-not-exist.json", 1)
		assert_nil(c)
		assert_eq(err.code, "no_credentials")
	end)
end)
