local config = require("config")

describe("config.resolve", function()
	it("merges nested thresholds and colors", function()
		local o = config.resolve({ thresholds = { warn = 50 }, colors = { warn = "#fff" } })
		assert_eq(o.thresholds.warn, 50)
		assert_eq(o.thresholds.crit, 90)
		assert_eq(o.colors.warn, "#fff")
		assert_eq(o.colors.crit, "#C8442E")
	end)
	it("replaces list options", function()
		local o = config.resolve({ sources = { "statusline" }, backoff = { 10 } })
		assert_eq(#o.sources, 1)
		assert_eq(o.backoff[1], 10)
	end)
	it("raises intervals below 120 with a warning", function()
		local warned
		local o = config.resolve({ interval = 10 }, function(m)
			warned = m
		end)
		assert_eq(o.interval, 120)
		assert_true(warned ~= nil)
	end)
	it("does not mutate defaults", function()
		config.resolve({ thresholds = { warn = 1 } })
		assert_eq(config.defaults.thresholds.warn, 75)
	end)
end)
