local H = require("spec.helpers")
local normalize = require("normalize")

describe("normalize.from_api (limits[] format)", function()
	local st = normalize.from_api(H.json("spec/fixtures/api_limits.json"), 1758560000)
	it("maps session and weekly windows", function()
		assert_eq(st.five_hour.percent, 3)
		assert_eq(st.five_hour.resets_at, 1790023800)
		assert_eq(st.five_hour.is_active, false)
		assert_eq(st.seven_day.percent, 67)
		assert_eq(st.seven_day.is_active, true)
	end)
	it("collects scoped weekly limits, naming by display_name or id, and borrows the weekly reset", function()
		assert_eq(#st.scoped, 2)
		assert_eq(st.scoped[1].name, "Fable")
		assert_eq(st.scoped[1].percent, 51)
		assert_eq(st.scoped[2].name, "claude-opus-5")
		assert_eq(st.scoped[2].percent, 0)
		assert_eq(st.scoped[2].resets_at, st.seven_day.resets_at)
	end)
	it("converts spend amounts", function()
		assert_eq(st.spend.enabled, true)
		assert_eq(st.spend.used, 12.34)
		assert_eq(st.spend.limit, 100)
		assert_eq(st.spend.currency, "USD")
		assert_eq(st.spend.percent, 12.34)
	end)
	it("keeps the breakdown", function()
		assert_eq(#st.breakdown, 3)
		assert_eq(st.breakdown[1].name, "Claude Code")
		assert_eq(st.breakdown[1].percent, 89)
	end)
	it("sets fetched_at to now", function()
		assert_eq(st.fetched_at, 1758560000)
		assert_true(normalize.has_data(st))
	end)
end)

describe("normalize.from_api (legacy format)", function()
	local st = normalize.from_api(H.json("spec/fixtures/api_legacy.json"), 1)
	it("uses utilization fields", function()
		assert_eq(st.five_hour.percent, 33)
		assert_eq(st.seven_day.percent, 13)
		assert_eq(st.five_hour.resets_at, 1775890800)
	end)
	it("maps seven_day_sonnet to a scoped entry", function()
		assert_eq(#st.scoped, 1)
		assert_eq(st.scoped[1].name, "Sonnet")
		assert_eq(st.scoped[1].percent, 1)
	end)
	it("reads extra_usage when spend is missing", function()
		assert_eq(st.spend.enabled, false)
	end)
end)

describe("normalize.from_api (edge cases)", function()
	it("tolerates garbage", function()
		local st = normalize.from_api(nil, 5)
		assert_true(not normalize.has_data(st))
		st = normalize.from_api({ limits = "nope", five_hour = { utilization = "abc" } }, 5)
		assert_true(not normalize.has_data(st))
	end)
	it("clamps negative percentages to zero", function()
		local st = normalize.from_api({ five_hour = { utilization = -4 } }, 5)
		assert_eq(st.five_hour.percent, 0)
	end)
end)

describe("normalize.from_statusline", function()
	local st = normalize.from_statusline(H.json("spec/fixtures/statusline.json"), 99)
	it("maps used_percentage and epoch seconds/milliseconds", function()
		assert_eq(st.five_hour.percent, 23.5)
		assert_eq(st.five_hour.resets_at, 1758570000)
		assert_eq(st.seven_day.resets_at, 1758900000)
	end)
	it("maps spend_limit and keeps percentages above 100", function()
		assert_eq(st.spend.enabled, true)
		assert_eq(st.spend.percent, 120.5)
	end)
	it("takes fetched_at from ts", function()
		assert_eq(st.fetched_at, 1758560000)
	end)
	it("falls back to now without ts", function()
		local s2 = normalize.from_statusline({ rate_limits = { five_hour = { used_percentage = 1 } } }, 7)
		assert_eq(s2.fetched_at, 7)
	end)
	it("treats a window missing from rate_limits as 0 % (not started)", function()
		local s2 = normalize.from_statusline({ rate_limits = { seven_day = { used_percentage = 9 } } }, 7)
		assert_eq(s2.five_hour.percent, 0)
		assert_eq(s2.five_hour.assumed, true)
		assert_nil(s2.five_hour.resets_at)
		assert_eq(s2.seven_day.assumed, nil)
		local s3 = normalize.from_statusline({ ts = 1, context = { used_percentage = 5 } }, 7)
		assert_nil(s3.five_hour)
		assert_true(not normalize.has_data(s3))
	end)
end)

describe("normalize.from_claude_json", function()
	it("reads the nested cache object", function()
		local st = normalize.from_claude_json(H.json("spec/fixtures/claude_json.json"), 1)
		assert_eq(st.seven_day.percent, 67)
		assert_eq(st.fetched_at, 1758490000)
		assert_eq(#st.scoped, 0)
	end)
	it("accepts the bare cachedUsageUtilization object", function()
		local raw = H.json("spec/fixtures/claude_json.json").cachedUsageUtilization
		local st = normalize.from_claude_json(raw, 1)
		assert_eq(st.five_hour.percent, 3)
	end)
end)
