local backoff = require("backoff")

describe("backoff", function()
	it("progresses through the schedule and repeats the last delay", function()
		local b = backoff.new({ 300, 600, 1200, 1800 })
		assert_eq(b:fail(0), 300)
		assert_eq(b:fail(0), 600)
		assert_eq(b:fail(0), 1200)
		assert_eq(b:fail(0), 1800)
		assert_eq(b:fail(0), 1800)
	end)
	it("blocks until the delay passed", function()
		local b = backoff.new({ 100 })
		assert_true(not b:blocked(0))
		b:fail(50)
		assert_true(b:blocked(100))
		assert_eq(b:remaining(100), 50)
		assert_true(not b:blocked(150))
		assert_eq(b:remaining(150), 0)
	end)
	it("resets", function()
		local b = backoff.new({ 100, 200 })
		b:fail(0)
		b:reset()
		assert_eq(b:fail(0), 100)
		assert_eq(b.attempt, 1)
	end)
end)
